### ISSUE TITLE
Month 2 Staking Payout Error 

### ISSUE THREAD

**Issue by PWalnuts** [manifoldfinance/support#5] opened 2022-04-20 11:24 UTC
Originally posted this yesterday elsewhere but have moved here as I think this is the most appropriate area. 

I staked on 21st Dec 2021 94.6 fold via dapp. I have not removed or added x fold since then. I have received payouts on Feb 6th (month 1), March 18th (month 3) and April 19th (month 4), however I was missed out on the month 2 payout.

My wallet is 0x73B1ccBba42E505eB969c356C7242A23c28ec15e

I have emailed a couple of times and you replied a few weeks ago to say that I recieved month 2 payout. Can you look into this as I believe that you were mistaken and that I am due month 2 payout.

https://etherscan.io/token/0xd084944d3c05cd115c09d072b9f44ba3e0e45921?a=0x73B1ccBba42E505eB969c356C7242A23c28ec15e shows the 3 payouts recieved

https://etherscan.io/token/0x454BD9E2B29EB5963048cC1A8BD6fD44e89899Cb?a=0x73B1ccBba42E505eB969c356C7242A23c28ec15e shows I have been staking for 4 months

Thanks

**Comment by sambacha** [comment] 2022-04-22 13:37
We pay staking on a rolling period basis, meaning its paid after the fact.

**Comment by PWalnuts** [comment] 2022-04-22 14:54
I'm genuinely confused, why did I not recieve a payout for month 2 on 17th February? I was issued with months 1, 3 and 4.

**Comment by PWalnuts** [comment] 2022-04-29 14:20
@sambacha thought I'd tag you in as it has been 7 days since my comment, thanks.

**Comment by sambacha** [comment] 2022-04-29 14:24
I will get this resolved no later than over this weekend, 💯 thanks for the reminder i have added it to my TODO.

**Comment by PWalnuts** [comment] 2022-05-07 22:09
@sambacha hi Sam, just a reminder that this is on your to do list. Thanks.

**Comment by sambacha** [comment] 2022-05-18 22:51
> @sambacha hi Sam, can you look into this

It will be fixed in this coming distribution sorry for not relaying that

**Comment by PWalnuts** [comment] 2022-05-23 20:27
@sambacha distribution took place and I haven't had a correction re the month 2 payout, could you let me know when this will be rectified please?

**Comment by sambacha** [comment] 2022-05-26 08:02
> @sambacha distribution took place and I haven't had a correction re the month 2 payout, could you let me know when this will be rectified please?

Can you provide me with an estimated amount so we can check our numbers against yours?

**Comment by PWalnuts** [comment] 2022-05-26 16:23
For the month 2 payout? According to Geerts analysis I was due for month 2 payout 3.2358142522914686 fold.

**Comment by PWalnuts** [comment] 2022-06-04 12:42
Hi @sambacha, how is this coming along? You had said this would be rectified during the last staking payout

**Comment by sambacha** [comment] 2022-06-04 15:54
Check back-in a few hrs it will be done

**Comment by PWalnuts** [comment] 2022-06-09 21:54
Hi @sambacha, you said the payout issue would be sorted in a few hours but it's been 5 days and I haven't recieved anything, could you advise please?

**Closed** 2022-06-16 19:24 UTC
Labels: bug

**Comment by dynsky** [comment] 2022-06-17 10:42
@PWalnuts https://etherscan.io/tx/0x4bdc14b3643ef5be0f13fb4aa030abb5812ac2a337d51d24b07de11b6843b7c5

**Comment by PWalnuts** [comment] 2022-06-18 22:22
HI @sambacha, I think Dynsky posted the link then deleted yesterday it as I have a gitguh email notification of the message. The link from Dynsky shows a payment that was made for 3. 2 Fold that does not got to my wallet. It seems clear there has been an error and my fold payment was sent to someone else. Can you confirm and make the payment to my wallet: 0x73B1ccBba42E505eB969c356C7242A23c28ec15e

**Comment by PWalnuts** [comment] 2022-06-26 21:09
@sambacha you have closed this without sending the rewards whilst claiming to have done so. I then recieved a proof of payment link from Dynsky that showed a payment to a completely unrelated wallet.

What is going on? This issue was raised over two months ago.

**Comment by sambacha** [comment] 2022-06-26 21:50
fixed, https://etherscan.io/tx/0xdca69a672399bcdf45592de74551d9217363917618577953e9a6d1d6611e10fa

thanks for following up, looks like the transaction failed and i (ofc) spoke too soon. 

This transaction has been confirmed, please let me know if they are any issues remaining

**Comment by PWalnuts** [comment] 2022-06-26 21:56
Thank you Sam, I appreciate your time on this matter and no issues remaing, all the best.
